PIA  NATAKA IWE AITK  LECTE ATTENACE  KWA JUU    KABLA YA  KU  WEKK COURSE  PAWE NA SEARCHBAR AMABYO  INAWEZA 
 AMBAPO CURSO ITAKUWA BY DEFULT IWE KWNEY SEARCHABR   AMABOPO  IN WAIT   IETHER LECURE TYPING ADMIN UMBE MANUAL 235050  OR KUTUMIA STUDENT ID CARD AMBOY  UKI SCNA KWNEY QRCORD SCANER INATOA  HIYO
  ADMIN NUMBER  YA HIYO STUDENT ID KADI  INAWEKA HAPO AMBP CURSO IPO  
   KWAHYO SERCH INAKUWA ACTIVE KUPKEA DATA  EITHER KWA KU TYPE AU KUTMIA 
   STUDENT ID  KWA KU SCNA QRCODE SCNAER AMBO INATOA  STUDENT  ADMN   KWNEY 
   SEACH BAR KHY KWAHYO  APO KWNRY SRACH BAR  CURSO ITAKIA INA LBINK IPO ACTIVE AMBPO  LECURE AKI FUNGU TU  VIEW YA  LECTE ATTENCE SERCHBA 
    AN MOUSE IWE ACTIVE IN BLIBK WAIT FRO INUPT  KWA KUWEKA ADMIN NUMBER AMBO LECURE ANWEZA KU TYPE ADMIN NUMBER  AU STUDENT  KU SCAN STUDET ID CARD KWNEY QR CORD AMBO HII INATOA HIYO ADMIN NUMBE NA KIWEKA KWNEY SEARNBAR AMBYO IPO ACIVE  KWAHYO

    SAS HAPO LARAVEL IATAFUTA JE  KUNA STUDENT AMBOY ADMIN NUMBE YAKO NI HII KAMA IPO ITAWEKA  PRESENT YANI   KAMA STUDENT  FOUND MWENYE HIYO ADMIN NUMBER 
     KAMA IPO ITA MARK PRESENT KWENYE DATABASE AMABO TULIWKE PRESNT NI AU NA ABSENT NI 0 KAMA HAKUNA MWNEY HIYO ADMIN NUMBER ISEMA NOT FOUND   
     KWAHYO HII NI FEAURE  INGINE YA PILI BAADAY YA LECURE KU TAKE ATTENACE MANUAL SASA ATATUMIA HII YA QRCODE KAMA NI OTPIN Y PILI
     A ALL THE BEST FANYA KZAI VIRUZI SASA KAZI IWE NZURI ZAIDI YA HAPA
